"""TFDS Dataset Builder for geebeam Earth Engine image chips."""

import tensorflow_datasets as tfds
import tensorflow as tf
from geebeam import ee_utils, sampler, transforms
import numpy as np
import ee


class _BuilderConfig(tfds.core.BuilderConfig):
    """Configuration object for builder."""
    def __init__(self, name, image_list, project_id, patch_size, scale, n_sample,
                 sampling_region, sampling_points, validation_ratio, crs,
                 random_seed, split_processing, extra_metadata):
        self.name = name
        self.image_list = image_list
        self.project_id = project_id
        self.patch_size = patch_size
        self.scale = scale
        self.n_sample = n_sample
        self.sampling_region = sampling_region
        self.sampling_points = sampling_points
        self.validation_ratio = validation_ratio
        self.crs = crs
        self.random_seed = random_seed
        self.split_processing = split_processing
        self.extra_metadata = extra_metadata
        self.extra_metadata_keys = list(extra_metadata.keys())
        self.all_bands = []  # Will be set later
        self.version = "0.0.1"
        self.supported_versions = ["0.0.1"]
        self.description = "foo"
        self.tags = []


class GeebeamDataset(tfds.core.GeneratorBasedBuilder):
    """TFDS Builder for geebeam Earth Engine image chips dataset."""

    RELEASE_NOTES = {
        '0.0.1': 'Initial release of geebeam TFDS dataset.',
    }

    def _info(self):
        """Define dataset info."""
        return tfds.core.DatasetInfo(
            builder=self,
            description="Earth Engine image chips dataset generated by geebeam",
            features=self._build_features(),
            supervised_keys=None,
            homepage="",
            citation="",
        )

    def _build_features(self):
        """Build feature dictionary from configuration."""
        config = self.builder_config
        patch_size = config.patch_size
        prepped_image, band_groups, all_bands = ee_utils.build_prepped_image(
            config.image_list, 
            split_processing=config.split_processing
        )
        self.all_bands = all_bands
        extra_keys = config.extra_metadata_keys
        
        features = {
            'md_id': tfds.features.Scalar(dtype=tf.int64),
            'md_y': tfds.features.Scalar(dtype=tf.float32),
            'md_x': tfds.features.Scalar(dtype=tf.float32),
            'md_split': tfds.features.Text(),
        }
        
        # Add extra metadata features
        for key in extra_keys:
            features[f'md_{key}'] = tfds.features.Scalar(dtype=tf.float32)
        
        # Add image band features
        for band in self.all_bands:
            features[f'im_{band}'] = tfds.features.Tensor(
                shape=(patch_size * patch_size,), 
                dtype=tf.float32
            )
        
        return tfds.features.FeaturesDict(features)

    def _split_generators(self, dl_manager):
        """Define splits based on training/validation ratio."""
        config = self.builder_config
        
        # Initialize Earth Engine
        ee.Initialize(project=config.project_id)
        
        # Get projection metadata
        proj = ee.Projection(config.crs).atScale(config.scale)
        proj_dict = proj.getInfo()
        scale_x = proj_dict['transform'][0]
        scale_y = -proj_dict['transform'][4]
        
        # Get sample points
        rng = np.random.default_rng(config.random_seed)
        if config.sampling_points is not None:
            sampled_points = sampler.process_sampling_points(
                config.sampling_points, 
                target_crs=config.crs
            )
        else:
            roi = sampler.get_roi(
                config.sampling_region, 
                config.image_list, 
                target_crs=config.crs
            )
            sampled_points = sampler.sample_random_points(
                roi, 
                config.n_sample, 
                rng
            )
        
        # Split into training and validation
        input_records = sampler.split_train_validation(
            sampled_points, 
            config.validation_ratio, 
            rng=rng
        ).to_dict('records')
        
        # Prepare and serialize image
        prepped_image, band_groups, all_bands = ee_utils.build_prepped_image(
            config.image_list, 
            split_processing=config.split_processing
        )
        serialized_image = ee_utils.serialize(prepped_image)
        
        # Store band names in config for later use
        # band_names = ee_utils.get_band_names(prepped_image)
        # all_bands = [band for group in band_groups for band in group]
        self.all_bands = list(all_bands)
        print(self.all_bands)
        
        return {
            'train': self._generate_examples(
                input_records=input_records,
                serialized_image=serialized_image,
                scale_x=scale_x,
                scale_y=scale_y,
                config=config,
                band_groups=band_groups,
                split='train'
            ),
            'validation': self._generate_examples(
                input_records=input_records,
                serialized_image=serialized_image,
                scale_x=scale_x,
                scale_y=scale_y,
                config=config,
                band_groups=band_groups,
                split='val'
            ) if config.validation_ratio > 0 else None,
        }

    def _generate_examples(self, input_records, serialized_image, scale_x, scale_y, 
                          config, band_groups, split):
        """Generate examples using Beam pipeline."""
        beam = tfds.core.lazy_imports.apache_beam
        
        def _filter_by_split(record):
            """Filter records by split."""
            return record.get('split') == split
        
        def _process_and_convert(record):
            """Process a record and convert to TFDS example format."""
            # Initialize EE in worker
            try:
                ee.Initialize(project=config.project_id,
                             opt_url='https://earthengine-highvolume.googleapis.com')
            except:
                pass  # Already initialized
            
            # Create config dict for EE processor
            ee_config = {
                'project_id': config.project_id,
                'patch_size': config.patch_size,
                'scale': config.scale,
                'n_sample': config.n_sample,
                'validation_ratio': config.validation_ratio,
                'crs': config.crs
            }
            
            # Create EE compute patch processor
            processor = transforms.EEComputePatch(
                ee_config,
                serialized_image,
                scale_x,
                scale_y,
                band_groups
            )
            processor.setup()
            
            # Process the record
            try:
                results = list(processor.process(record))
                if results:
                    out_dict = results[0]
                    # print(out_dict)
                    
                    # Add extra metadata
                    merged_metadata = {
                        **out_dict.get("metadata", {}),
                        **config.extra_metadata
                    }
                    
                    # Convert dict to TFDS example format
                    example = {}
                    
                    # Add metadata
                    example['md_id'] = merged_metadata['id']
                    example['md_y'] = merged_metadata['y']
                    example['md_x'] = merged_metadata['x']
                    example['md_split'] = merged_metadata['split']
                    
                    # Add extra metadata
                    for key in config.extra_metadata.keys():
                        if key in merged_metadata:
                            example[f'md_{key}'] = merged_metadata[key]
                    
                    # Add image bands
                    for band_name, band_data in out_dict['array'].items():
                        example[f'im_{band_name}'] = band_data.flatten().astype('float32')
                    # print(example)
                    
                    return record['id'], example
            except Exception as e:
                import logging
                logging.error(f"Error processing record {record['id']}: {e}")
                raise
        
        return (
            beam.Create(input_records)
            | f'Filter {split}' >> beam.Filter(_filter_by_split) 
            | f'Reshuffle {split}' >> beam.Reshuffle()
            | f'Process {split}' >> beam.Map(_process_and_convert)
        )

