name: Create and publish a Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REPO_NAME: geebeam

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets up permissions
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Dockerhub
        uses: docker/login-action@4a8376e001c7725687f0624d1c3698a3f6ab337e
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@a7807070e67ad478bd5f672f499303a151742e53
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@83bfd93ab480705a7b99a2ed02765137f5ab55ba
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
