name: Create and publish a Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REPO_NAME: geebeam

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets up permissions
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Dockerhub
        uses: docker/login-action@17f7c1809f7467d4244b4ff01b0dbe0b8b9e3d43
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3caf19fbe3db1a1a6a8bdce189e09ac0ed35d513
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@1d0c110a5d679453d30b396aa86f6bb6ae377b76
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
